# Generated by Django 5.0.6 on 2024-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shirt_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
