# Generated by Django 5.0.6 on 2024-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
