# Generated by Django 5.0.6 on 2024-06-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
